version: "3.8"
services:
  public:
    container_name: snappy-chat-public
    image: prafuldevops/snappy-chat-public
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: always
    networks:
      - snappy-chat-network
    environment:
      - ENV_VAR=example
  server:
    container_name: snappy-chat-server
    image: prafuldevops/snappy-chat-server
    networks:
      - snappy-chat-network
    restart: always
    environment:
      MONGO_URL: mongodb://root:root_password@db:27017/snappy_db?authSource=admin
      BACKEND_PORT: 5000
    depends_on:
       db:
         condition: service_healthy

  db:
    container_name: snappy-chat-db
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: snappy_db
    networks:
      - snappy-chat-network
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  snappy-chat-network: 
volumes:
  mongo_data:
