apiVersion: apps/v1
kind: Deployment
metadata:
  name: snappy
  namespace: snappy-chat-app
spec:
  selector:
    matchLabels:
      app: snappy-app-server
  template:
    metadata:
      labels:
        app: snappy-app-server
    spec:
      containers:
      - name: snappy-chat-server
        image: prafuldevops/snappy-chat-server
        env:
        - name: MONGO_URL
          value: "mongodb://root:root_password@db:27017/snappy_db?authSource=admin"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
